# Study Recruitment {.unnumbered}

Participants were recruited from Madison and the surrounding area.

## Recruitment sites

Five local treatment sites across two large healthcare centers partnered with ARC for recruitment: <a href="https://accesscommunityhealthcenters.org/">Access Community Health Centers</a> and <a href="https://www.journeymhc.org/">Journey Mental Health Center</a>.

These sites were selected to support recruitment of a diverse set of patients (e.g., both genders; racially diverse; AUD only vs. dual diagnosis). They were also selected to provide adequate patient flow for study recruitment and patient access to the study site in Madison, WI. 


## Advertising

Recruitment of the community at large was conducted by posting flyers or ads in places likely to be seen by the target population (Alcoholics Anonymous meetings, Metro buses, and online using sites like Facebook and Craigslist). The goal of community recruitment is to include participants using a wider variety of treatment methods to achieve sobriety, ranging from the structured clinical outpatient visits at the above recruiting sites, to self-directed abstinence methods without formal support.